<HomeScreen>:
    BoxLayout:
        orientation: "vertical"

        Label:
            text: "Aproxime um cartão RFID"

            font_size: 40


<EletronScreen>:
    BoxLayout:
        orientation: "vertical"

        Label:
            text: "ELÉTRON"

            font_size: 60

        Label:
            text: "Carga elétrica negativa"


<MuonScreen>:
    BoxLayout:
        orientation: "vertical"

        Label:
            text: "MÚON"

            font_size: 60

        Label:
            text: "Lépton semelhante ao elétron"


<QuarkScreen>:
    BoxLayout:
        orientation: "vertical"

        Label:
            text: "QUARK"

            font_size: 60

        Label:
            text: "Partícula fundamental da matéria"